bot:
  token:
  name: FreeLC
  admin:
  number:

server:
  port: 5432

spring:
  liquibase:
    enabled: true
    contexts: test
  jpa:
    properties:
      hibernate.show_sql: false
      hibernate:format_sql: false
    open-in-view: false
    hibernate.ddl-auto: none
  datasource:
    #  Note that the hostname, port and database name on url property and username and password properties will be ignored
    #  and it will be used default container values
    url:
    driver-class-name: org.postgresql.Driver
    username:
    password:
    hikari:
      schema: public