bot:
  token: 1727348060:AAHks0ViKIAPzPoOqKPjpygvw2lTJSpsjkM
  name: FreeLC
  admin: 218331443
  number: +7 (495) 640 -63 - 55

server:
  port: 5432

spring:
  liquibase:
    enabled: true
    contexts: test
  jpa:
    properties:
      hibernate.show_sql: false
      hibernate:format_sql: false
    open-in-view: false
    hibernate.ddl-auto: none
  datasource:
    #  Note that the hostname, port and database name on url property and username and password properties will be ignored
    #  and it will be used default container values
    url: jdbc:postgresql://localhost:5432/bot?user=nikita&password=91823God&currentSchema=public
    driver-class-name: org.postgresql.Driver
    username: nikita
    password: 91823God
    hikari:
      schema: public